DROP TABLE IF EXISTS `dazhongdianping_meishi_shop`;
CREATE TABLE `dazhongdianping_meishi_shop` (
  `adInfo` text,
  `altName` varchar(100),
  `authorityLabelType` int(10),
  `bookType` varchar(10),
  `branchName` varchar(100),
  `categoryId` int(10),
  `categoryName` varchar(100),
  `cityId` int(100) NOT NULL,
  `defaultPic` text,
  `dishtags` text,
  `extraJson` text,
  `shopDealInfos` text,
  `id` bigint(100) NOT NULL,
  `matchText` text,
  `memberCardId` int(100),
  `name` varchar(1000) NOT NULL,
  `newShop` varchar(100),
  `orderDish` varchar(100),
  `originalUrlKey` text,
  `priceText` varchar(200),
  `recommendReasonData` text,
  `regionName` varchar(1000),
  `reviewCount` bigint(100),
  `scoreText` varchar(1000),
  `shopPositionInfo` text,
  `shopPower` int(100),
  `shopStateInformation` text,
  `shopType` int(100),
  `status` int(100),
  `tag` text,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;