DROP TABLE IF EXISTS `elong_shop`;
CREATE TABLE `elong_shop` (
  `activityTags` text,
  `baiduLatitude` varchar(100),
  `baiduLongitude` varchar(100),
  `businessAreaName` varchar(100),
  `calDistanceType` int(100),
  `commentPoint` varchar(100),
  `commentScore` int(100),
  `id` int(100) NOT NULL,
  `distance` varchar(100),
  `distanceName` varchar(100),
  `districtName` varchar(100),
  `facilityList` text,
  `hongbao` int(100),
  `hotelBadge` int(100),
  `hotelName` varchar(100),
  `leftRoomCountShow` varchar(100),
  `lmOriPrice` int(100),
  `lowestPrice` int(100),
  `minPriceInventories` varchar(100),
  `minPriceSubCouponInventories` varchar(100),
  `newRecallReason` varchar(100),
  `picUrl` text,
  `placeName` varchar(100),
  `specialDay` varchar(100),
  `starLevel` int(100),
  `syncfacilityList` text,
  `tags` text,
  `totalCommentCount` int(100),
  `trafficInfo` varchar(100),
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;